// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item.proto

/*
Package gcache is a generated protocol buffer package.

It is generated from these files:
	item.proto

It has these top-level messages:
	TransportItem
*/
package gcache

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TransportItem_Commands int32

const (
	TransportItem_SET   TransportItem_Commands = 0
	TransportItem_GET   TransportItem_Commands = 1
	TransportItem_PURGE TransportItem_Commands = 2
	TransportItem_DEAD  TransportItem_Commands = 3
)

var TransportItem_Commands_name = map[int32]string{
	0: "SET",
	1: "GET",
	2: "PURGE",
	3: "DEAD",
}
var TransportItem_Commands_value = map[string]int32{
	"SET":   0,
	"GET":   1,
	"PURGE": 2,
	"DEAD":  3,
}

func (x TransportItem_Commands) String() string {
	return proto.EnumName(TransportItem_Commands_name, int32(x))
}
func (TransportItem_Commands) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type TransportItem struct {
	Command    TransportItem_Commands `protobuf:"varint,1,opt,name=Command,json=command,enum=gcache.TransportItem_Commands" json:"Command,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=Name,json=name" json:"Name,omitempty"`
	Expiration int64                  `protobuf:"zigzag64,3,opt,name=Expiration,json=expiration" json:"Expiration,omitempty"`
	Object     []byte                 `protobuf:"bytes,4,opt,name=Object,json=object,proto3" json:"Object,omitempty"`
}

func (m *TransportItem) Reset()                    { *m = TransportItem{} }
func (m *TransportItem) String() string            { return proto.CompactTextString(m) }
func (*TransportItem) ProtoMessage()               {}
func (*TransportItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TransportItem) GetCommand() TransportItem_Commands {
	if m != nil {
		return m.Command
	}
	return TransportItem_SET
}

func (m *TransportItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TransportItem) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

func (m *TransportItem) GetObject() []byte {
	if m != nil {
		return m.Object
	}
	return nil
}

func init() {
	proto.RegisterType((*TransportItem)(nil), "gcache.TransportItem")
	proto.RegisterEnum("gcache.TransportItem_Commands", TransportItem_Commands_name, TransportItem_Commands_value)
}

func init() { proto.RegisterFile("item.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x8f, 0xb1, 0x4a, 0x04, 0x31,
	0x18, 0x84, 0xcd, 0x6d, 0xcc, 0xde, 0xfd, 0xa8, 0x84, 0xbf, 0x90, 0x54, 0x47, 0xb8, 0x2a, 0x55,
	0x40, 0x6d, 0x6c, 0xc5, 0x0b, 0x87, 0x8d, 0x4a, 0x5c, 0x1f, 0x20, 0x1b, 0x83, 0xae, 0x90, 0x64,
	0xc9, 0xa6, 0xf0, 0x11, 0x7d, 0x2c, 0x71, 0x57, 0x05, 0xbb, 0x6f, 0x86, 0x0f, 0x86, 0x01, 0x18,
	0x6a, 0x88, 0x7a, 0x2c, 0xb9, 0x66, 0x64, 0xaf, 0xde, 0xf9, 0xb7, 0xb0, 0xfb, 0x24, 0x70, 0xda,
	0x15, 0x97, 0xa6, 0x31, 0x97, 0x7a, 0x57, 0x43, 0xc4, 0x6b, 0x68, 0x6f, 0x73, 0x8c, 0x2e, 0xbd,
	0x08, 0x22, 0x89, 0x3a, 0xbb, 0xdc, 0xea, 0xc5, 0xd5, 0xff, 0x3c, 0xfd, 0x23, 0x4d, 0xb6, 0xf5,
	0x0b, 0x21, 0x02, 0xbd, 0x77, 0x31, 0x88, 0x95, 0x24, 0x6a, 0x63, 0x69, 0x72, 0x31, 0xe0, 0x16,
	0xc0, 0x7c, 0x8c, 0x43, 0x71, 0x75, 0xc8, 0x49, 0x34, 0x92, 0x28, 0xb4, 0x10, 0xfe, 0x1a, 0x3c,
	0x07, 0xf6, 0xd0, 0xbf, 0x07, 0x5f, 0x05, 0x95, 0x44, 0x9d, 0x58, 0x96, 0xe7, 0xb4, 0xbb, 0x80,
	0xf5, 0xef, 0x00, 0xb6, 0xd0, 0x3c, 0x99, 0x8e, 0x1f, 0x7d, 0xc3, 0xc1, 0x74, 0x9c, 0xe0, 0x06,
	0x8e, 0x1f, 0x9f, 0xed, 0xc1, 0xf0, 0x15, 0xae, 0x81, 0xee, 0xcd, 0xcd, 0x9e, 0x37, 0x3d, 0x9b,
	0x9f, 0x5d, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x86, 0x1d, 0x01, 0xe7, 0x00, 0x00, 0x00,
}
